version: "3.9"
services:
  gowebserver:
    image: "rpot/demo-app-gowebserver:${TAG}"
    build: "./gowebserver"
    expose:
      - "8080"
    environment:
      WORKSPACE: ${WORKSPACE:-test}

  gateway:
    image: "rpot/demo-app-gateway:${TAG}"
    build: "./gateway"
    ports:
      - "80:80"
    depends_on:
      - "gowebserver"
