apiVersion: v1
kind: Service
metadata:
  name: demo-gateway-node-port
  labels:
    app: demo-gateway
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
  - port: {{ .Values.gateway.service.port }}
    targetPort: 80
  selector:
    app: demo-gateway
