apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gowebserver.service.name }}
  labels:
    app: demo-gowebserver
spec:
  selector:
    app: demo-gowebserver
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
