{{- if .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-gateway-ingress
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  rules:
  - {{ if .Values.ingress.host }}host: {{ .Values.ingress.host }} {{ end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-gateway-node-port
            port:
              number: {{ .Values.ingress.port }}
  {{- if .Values.ingress.tlsSecretName }}
  tls:
  - secretName: {{ .Values.ingress.tlsSecretName }}
    {{- if .Values.ingress.host }}
    hosts:
    - {{ .Values.ingress.host }}
    {{- end }}
  {{- end }}
{{ end }}
